version: '3.4'

services:
  albelli.shop.api:
    image: ${DOCKER_REGISTRY-}albellishopapi
    build:
      context: .
      dockerfile: Albelli.Shop.Api/Dockerfile
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "9000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
